#!/usr/bin/env python3
"""Tests for digest.py against throwaway git repositories.

Run from the skill directory:
    python3 -m unittest scripts/test_digest.py
    python3 scripts/test_digest.py
"""

from __future__ import annotations

import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import build_tour  # noqa: E402  (needs sys.path set up above)
import digest  # noqa: E402
import pagelib  # noqa: E402  (on sys.path once digest is imported)

A_TS = """import { fetchUser } from "./api";

export function show(id) {
  const user = fetchUser(id);
  return user.name;
}
"""

B_TS = """import { fetchUser } from "./api";

export async function refresh(ids) {
  for (const id of ids) {
    await fetchUser(id);
  }
}
"""

C_TS = """// fetchUser is the only reader of the users table.
export const reader = "fetchUser";
"""

SAVE_TS = """import { fetchUser } from "./api";

export function save(user) {
  if (!user.ok) return;
  fetchUser(user.id);
  write(user);
}
"""

SAVE_TS_GUARD_MOVED = """import { loadUser } from "./api";

export function save(user) {
  loadUser(user.id);
  write(user);
  if (!user.ok) return;
}
"""


def renamed(text: str) -> str:
    return text.replace("fetchUser", "loadUser")


def git(repo: Path, *args: str) -> str:
    out = subprocess.run(
        ["git", "-C", str(repo), "-c", "commit.gpgsign=false", *args], capture_output=True, text=True
    )
    if out.returncode != 0:
        raise AssertionError(f"git {' '.join(args)} failed: {out.stderr}")
    return out.stdout.strip()


class Repo:
    def __init__(self, path: Path) -> None:
        self.path = path
        path.mkdir()
        git(path, "init", "-q", "-b", "main")
        # a fixture commit must never land in an enclosing repository
        top = Path(git(path, "rev-parse", "--show-toplevel")).resolve()
        if top != path.resolve():
            raise AssertionError(f"fixture repo resolved to {top}, not {path}")
        git(path, "config", "user.name", "Digest Test")
        git(path, "config", "user.email", "test@example.invalid")
        git(path, "config", "commit.gpgsign", "false")

    def put(self, files: dict[str, str | bytes | None]) -> None:
        for rel, body in files.items():
            p = self.path / rel
            if body is None:
                p.unlink()
                continue
            p.parent.mkdir(parents=True, exist_ok=True)
            if isinstance(body, bytes):
                p.write_bytes(body)
            else:
                p.write_text(body, encoding="utf-8")

    def commit(self, msg: str) -> str:
        git(self.path, "add", "-A")
        git(self.path, "commit", "-q", "--no-verify", "--allow-empty", "-m", msg)
        return git(self.path, "rev-parse", "HEAD")


def chapter(cid: str, risk: str, *paths: str) -> dict:
    return {"id": cid, "title": cid.title(), "risk": risk, "overview": "<p>x</p>", "files": [{"path": p} for p in paths]}


def sub_group(gid: str, globs: list[str], frm: str, to: str, **extra: object) -> dict:
    return {"id": gid, "title": f"{gid} rule", "files": globs, "from": frm, "to": to, **extra}


def word_group(gid: str, globs: list[str], kind: str = "generated") -> dict:
    return {"id": gid, "title": f"{gid} files", "files": globs, "kind": kind, "why": "Regenerated by the build."}


def make_spec(groups: list[dict] = (), chapters: list[dict] = (), everything_else: list[str] = ()) -> dict:
    return {
        "chapters": list(chapters) or [chapter("core", "attention")],
        "groups": list(groups),
        "everythingElse": [{"path": p, "why": "Along for the ride."} for p in everything_else],
    }


def group_of(d: digest.Digest, gid: str) -> digest.Group:
    for g in d.groups:
        if g.id == gid:
            return g
    raise AssertionError(f"no group {gid}; have {[g.id for g in d.groups]}")


class DigestCase(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.repo = Repo(Path(self.tmp.name) / "repo")
        self.base = ""
        self.head = ""

    def make(self, base: dict[str, str | bytes], head: dict[str, str | bytes | None]) -> None:
        self.repo.put(base)
        self.base = self.repo.commit("base")
        self.repo.put(head)
        self.head = self.repo.commit("head")

    def classify(self, spec: dict, head: str | None = None, seed: int = 0) -> digest.Digest:
        head = head or self.head
        files = build_tour.load_changed_files(self.repo.path, self.base, head)
        return digest.classify(spec, files, self.repo.path, self.base, head, seed)

    def fails(self, spec: dict, head: str | None = None) -> str:
        with self.assertRaises(pagelib.BuildFailed) as cm:
            self.classify(spec, head)
        return cm.exception.msg


class SubstitutionTest(DigestCase):
    def rename_fixture(self, **overrides: str) -> None:
        base = {"src/a.ts": A_TS, "src/b.ts": B_TS, "src/c.ts": C_TS}
        head = {path: renamed(text) for path, text in base.items()}
        head.update(overrides)
        self.make(base, head)

    def test_rename_across_files_is_matched(self) -> None:
        self.rename_fixture()
        d = self.classify(make_spec([sub_group("rename", ["src/*.ts"], "fetchUser", "loadUser")]))
        g = group_of(d, "rename")
        self.assertEqual((g.kind, g.tier), ("substitution", "matched"))
        self.assertEqual(g.files, ["src/a.ts", "src/b.ts", "src/c.ts"])
        self.assertEqual(g.rule, {"from": "fetchUser", "to": "loadUser", "regex": False})
        self.assertEqual(d.flags, [])
        self.assertEqual(d.tiers, {"src/a.ts": "matched", "src/b.ts": "matched", "src/c.ts": "matched"})
        # first file in path order, its first run (line 1), widened by 2 and clamped at the top
        self.assertEqual(g.samples, [digest.Sample("src/a.ts", "new", 1, 3)])

    def test_extra_call_on_a_renamed_line_is_flagged(self) -> None:
        bad = renamed(A_TS).replace("loadUser(id);", "loadUser(id) || deleteAll();")
        self.rename_fixture(**{"src/a.ts": bad})
        d = self.classify(make_spec([sub_group("rename", ["src/*.ts"], "fetchUser", "loadUser")]))
        self.assertEqual(d.tiers["src/a.ts"], "flagged")
        self.assertEqual(group_of(d, "rename").files, ["src/b.ts", "src/c.ts"])
        [flag] = d.flags
        self.assertEqual((flag.path, flag.group), ("src/a.ts", "rename"))
        self.assertEqual(flag.reason, "Applying the rule to the old file does not give the new file.")
        self.assertEqual(
            flag.blocks, [(4, ["  const user = loadUser(id);"], ["  const user = loadUser(id) || deleteAll();"])]
        )

    def test_guard_moved_below_the_write_is_flagged(self) -> None:
        # the same multiset of lines as a clean rename; only the order is wrong
        self.assertEqual(sorted(renamed(SAVE_TS).splitlines()), sorted(SAVE_TS_GUARD_MOVED.splitlines()))
        self.make({"src/save.ts": SAVE_TS, "src/a.ts": A_TS}, {"src/save.ts": SAVE_TS_GUARD_MOVED, "src/a.ts": renamed(A_TS)})
        d = self.classify(make_spec([sub_group("rename", ["src/*.ts"], "fetchUser", "loadUser")]))
        self.assertEqual(d.tiers["src/save.ts"], "flagged")
        self.assertEqual(d.tiers["src/a.ts"], "matched")
        [flag] = d.flags
        self.assertEqual(flag.path, "src/save.ts")
        self.assertTrue(flag.blocks)
        self.assertIn("  if (!user.ok) return;", [line for b in flag.blocks for line in b[1] + b[2]])

    def test_partial_rename_is_flagged_and_the_group_stays(self) -> None:
        partial = renamed(A_TS).replace("const user = loadUser(id);", "const user = fetchUser(id);")
        self.make({"src/a.ts": A_TS}, {"src/a.ts": partial})
        d = self.classify(make_spec([sub_group("rename", ["src/*.ts"], "fetchUser", "loadUser")]))
        self.assertEqual(d.tiers, {"src/a.ts": "flagged"})
        g = group_of(d, "rename")
        self.assertEqual((g.files, g.samples), ([], []))
        [flag] = d.flags
        self.assertEqual(flag.blocks, [(4, ["  const user = loadUser(id);"], ["  const user = fetchUser(id);"])])

    def test_regex_backreference_matches(self) -> None:
        self.make(
            {"api.py": "a = getUserId(x)\nb = getOrderId(y)\n"},
            {"api.py": "a = fetchUserKey(x)\nb = fetchOrderKey(y)\n"},
        )
        rule = sub_group("ids", ["api.py"], r"get(\w+)Id\(", r"fetch\1Key(", regex=True)
        d = self.classify(make_spec([rule]))
        self.assertEqual(d.tiers, {"api.py": "matched"})
        self.assertEqual(group_of(d, "ids").rule, {"from": r"get(\w+)Id\(", "to": r"fetch\1Key(", "regex": True})

    def test_plain_rule_takes_backslashes_literally(self) -> None:
        self.make({"paths.py": "root = 'C:/old'\n"}, {"paths.py": "root = 'C:\\new'\n"})
        d = self.classify(make_spec([sub_group("win", ["paths.py"], "C:/old", "C:\\new")]))
        self.assertEqual(d.tiers, {"paths.py": "matched"})

    def test_mode_change_is_flagged(self) -> None:
        self.repo.put({"src/a.ts": A_TS})
        self.base = self.repo.commit("base")
        self.repo.put({"src/a.ts": renamed(A_TS)})
        os.chmod(self.repo.path / "src/a.ts", 0o755)
        self.head = self.repo.commit("head")
        d = self.classify(make_spec([sub_group("rename", ["src/*.ts"], "fetchUser", "loadUser")]))
        [flag] = d.flags
        self.assertEqual(flag.reason, "The file mode changed from 100644 to 100755.")
        self.assertEqual(flag.blocks, [])
        self.assertEqual(d.tiers, {"src/a.ts": "flagged"})

    def test_new_deleted_binary_and_copied_files_are_flagged(self) -> None:
        git(self.repo.path, "config", "diff.renames", "copies")
        self.make(
            {"src/gone.ts": C_TS, "src/img.ts": b"\0fetchUser", "src/orig.ts": B_TS},
            {
                "src/gone.ts": None,
                "src/img.ts": b"\0loadUser",
                "src/new.ts": "export const fresh = loadUser;\n",
                "src/orig.ts": renamed(B_TS),
                "src/copy.ts": B_TS,
            },
        )
        files = build_tour.load_changed_files(self.repo.path, self.base, self.head)
        self.assertEqual(files["src/copy.ts"].status, "C")
        d = self.classify(make_spec([sub_group("rename", ["src/*.ts"], "fetchUser", "loadUser")]))
        reasons = {f.path: f.reason for f in d.flags}
        self.assertEqual(
            reasons,
            {
                "src/copy.ts": "A copy adds code, so a rule cannot explain it.",
                "src/gone.ts": "This file is deleted, so a rule cannot explain it.",
                "src/img.ts": "This file is binary, so a rule cannot explain it.",
                "src/new.ts": "This file is new, so a rule cannot explain it.",
            },
        )
        self.assertEqual([f.path for f in d.flags], sorted(reasons))
        self.assertEqual(group_of(d, "rename").files, ["src/orig.ts"])


class CheckGroupsTest(unittest.TestCase):
    def check(self, group: dict, chapter_ids: set[str] = frozenset({"core"})) -> str:
        with self.assertRaises(pagelib.BuildFailed) as cm:
            digest.check_groups({"groups": [group]}, set(chapter_ids))
        return cm.exception.msg

    def test_valid_groups_pass(self) -> None:
        digest.check_groups(
            {"groups": [sub_group("a", ["x/*"], "f", ""), word_group("b", ["y/*"], "lockfile")]}, {"core"}
        )
        digest.check_groups({}, {"core"})

    def test_invalid_regex_fails(self) -> None:
        msg = self.check(sub_group("ids", ["*"], "get(", "x", regex=True))
        self.assertIn("group ids", msg)
        self.assertIn("regex", msg)

    def test_invalid_regex_template_fails(self) -> None:
        msg = self.check(sub_group("ids", ["*"], "get", r"\9", regex=True))
        self.assertIn("group ids", msg)

    def test_reserved_id_fails(self) -> None:
        for gid in digest.DERIVED_IDS:
            self.assertIn(gid, self.check(sub_group(gid, ["*"], "a", "b")))

    def test_id_equal_to_a_chapter_id_fails(self) -> None:
        self.assertIn("group core", self.check(sub_group("core", ["*"], "a", "b")))

    def test_duplicate_group_id_fails(self) -> None:
        with self.assertRaises(pagelib.BuildFailed) as cm:
            digest.check_groups({"groups": [sub_group("a", ["*"], "x", "y"), word_group("a", ["*"])]}, set())
        self.assertIn("group a", cm.exception.msg)

    def test_shape_defects_fail(self) -> None:
        bad = [
            {"id": "", "title": "t", "files": ["*"], "from": "a", "to": "b"},
            {"id": "g", "title": "", "files": ["*"], "from": "a", "to": "b"},
            {"id": "g", "title": "t", "files": [], "from": "a", "to": "b"},
            {"id": "g", "title": "t", "files": [""], "from": "a", "to": "b"},
            {"id": "g", "title": "t", "files": "*", "from": "a", "to": "b"},
            {"id": "g", "title": "t", "files": ["*"], "from": "", "to": "b"},
            {"id": "g", "title": "t", "files": ["*"], "from": "a"},
            {"id": "g", "title": "t", "files": ["*"], "from": "a", "to": "b", "regex": "yes"},
            {"id": "g", "title": "t", "files": ["*"], "kind": "generated"},
            {"id": "g", "title": "t", "files": ["*"], "kind": "vendored", "why": "w"},
            {"id": "g", "title": "t", "files": ["*"], "kind": "bulk", "why": "w", "from": "a", "to": "b"},
            {"id": "g", "title": "t", "files": ["*"]},
        ]
        for group in bad:
            with self.subTest(group=group):
                self.check(group)


class PlacementTest(DigestCase):
    def setUp(self) -> None:
        super().setUp()
        self.make({"src/a.ts": A_TS, "src/b.ts": B_TS}, {"src/a.ts": renamed(A_TS), "src/b.ts": renamed(B_TS)})

    def test_chapter_beats_glob(self) -> None:
        spec = make_spec(
            [sub_group("rename", ["src/*.ts"], "fetchUser", "loadUser")], [chapter("core", "attention", "src/a.ts")]
        )
        d = self.classify(spec)
        self.assertEqual(d.tiers, {"src/a.ts": "read", "src/b.ts": "matched"})
        self.assertEqual(group_of(d, "rename").files, ["src/b.ts"])

    def test_two_groups_on_one_path_fail(self) -> None:
        spec = make_spec([sub_group("one", ["src/*.ts"], "a", "b"), word_group("two", ["src/a.ts"])])
        self.assertEqual(self.fails(spec), "src/a.ts matches groups one and two; keep it in one")

    def test_dead_glob_fails(self) -> None:
        msg = self.fails(make_spec([sub_group("rename", ["src/*.ts", "lib/*.ts"], "fetchUser", "loadUser")]))
        self.assertIn("group rename", msg)
        self.assertIn("lib/*.ts", msg)

    def test_group_emptied_by_chapters_fails(self) -> None:
        spec = make_spec(
            [sub_group("rename", ["src/*.ts"], "fetchUser", "loadUser")],
            [chapter("core", "attention", "src/a.ts", "src/b.ts")],
        )
        self.assertIn("group rename", self.fails(spec))

    def test_everything_else_under_a_glob_fails(self) -> None:
        spec = make_spec([sub_group("rename", ["src/*.ts"], "fetchUser", "loadUser")], everything_else=["src/b.ts"])
        msg = self.fails(spec)
        self.assertIn("src/b.ts", msg)
        self.assertIn("rename", msg)

    def test_reserved_id_fails_in_classify(self) -> None:
        self.assertIn("moved", self.fails(make_spec([word_group("moved", ["src/*.ts"])])))

    def test_star_crosses_slashes(self) -> None:
        d = self.classify(make_spec([sub_group("rename", ["*.ts"], "fetchUser", "loadUser")]))
        self.assertEqual(group_of(d, "rename").files, ["src/a.ts", "src/b.ts"])


class DerivedTest(DigestCase):
    def test_line_ends(self) -> None:
        self.make(
            {
                "dedent.py": "def f():\n        return 1\n",
                "trail.py": "x = 1   \ny = 2\n",
                "notes.md": "Line one.  \nLine two.\n",
            },
            {
                "dedent.py": "def f():\n    return 1\n",
                "trail.py": "x = 1\ny = 2\n",
                "notes.md": "Line one.\nLine two.\n",
            },
        )
        self.assertEqual(self.fails(make_spec()), "changed files no chapter or group claims: dedent.py, notes.md")
        d = self.classify(make_spec(everything_else=["dedent.py", "notes.md"]))
        g = group_of(d, "line-ends")
        self.assertEqual((g.files, g.kind, g.tier), (["trail.py"], "line-ends", "matched"))
        self.assertEqual(g.samples, [digest.Sample("trail.py", "new", 1, 2)])
        self.assertEqual(d.tiers["trail.py"], "matched")
        self.assertEqual(group_of(d, "everything-else").files, ["dedent.py", "notes.md"])

    def test_moved(self) -> None:
        git(self.repo.path, "config", "diff.renames", "copies")
        os.symlink("a.txt", self.repo.path / "link")
        self.repo.put({"a.txt": "alpha\n" * 5, "run.sh": "echo run\n" * 5, "src.txt": "source line\n" * 5})
        self.base = self.repo.commit("base")
        git(self.repo.path, "mv", "a.txt", "moved-a.txt")
        git(self.repo.path, "mv", "run.sh", "run2.sh")
        os.chmod(self.repo.path / "run2.sh", 0o755)
        git(self.repo.path, "mv", "link", "link2")
        self.repo.put({"copy.txt": "source line\n" * 5, "src.txt": "source line\n" * 5 + "more\n"})
        self.head = self.repo.commit("head")
        files = build_tour.load_changed_files(self.repo.path, self.base, self.head)
        self.assertEqual(
            {p: fd.status for p, fd in files.items()},
            {"moved-a.txt": "R", "run2.sh": "R", "link2": "R", "copy.txt": "C", "src.txt": "M"},
        )
        self.assertEqual(
            self.fails(make_spec(everything_else=["src.txt"])),
            "changed files no chapter or group claims: copy.txt, link2, run2.sh",
        )
        d = self.classify(make_spec(everything_else=["src.txt", "copy.txt", "link2", "run2.sh"]))
        g = group_of(d, "moved")
        self.assertEqual((g.files, g.kind, g.tier, g.samples), (["moved-a.txt"], "moved", "matched", []))

    def test_deleted_and_binary(self) -> None:
        self.make(
            {"old.txt": "bye\n", "img.bin": b"\0\1\2", "gone.bin": b"\0\0"},
            {"old.txt": None, "img.bin": b"\0\1\3", "gone.bin": None},
        )
        d = self.classify(make_spec())
        self.assertEqual([g.id for g in d.groups], ["deleted", "binary"])
        self.assertEqual(group_of(d, "deleted").files, ["gone.bin", "old.txt"])
        self.assertEqual(group_of(d, "binary").files, ["img.bin"])
        for g in d.groups:
            self.assertEqual((g.kind, g.tier, g.samples), (g.id, "word", []))
        self.assertEqual(set(d.tiers.values()), {"word"})

    def test_worktree_rename_and_staged_move(self) -> None:
        self.repo.put({"src/a.ts": A_TS, "src/b.ts": B_TS, "plain.txt": "plain\n" * 3})
        self.base = self.repo.commit("base")
        self.repo.put({"src/a.ts": renamed(A_TS), "src/b.ts": renamed(B_TS), "src/new.ts": renamed(A_TS)})
        (self.repo.path / "moved").mkdir()
        git(self.repo.path, "mv", "plain.txt", "moved/plain.txt")
        d = self.classify(make_spec([sub_group("rename", ["src/*.ts"], "fetchUser", "loadUser")]), head="worktree")
        self.assertEqual(group_of(d, "rename").files, ["src/a.ts", "src/b.ts"])
        self.assertEqual(group_of(d, "moved").files, ["moved/plain.txt"])
        [flag] = d.flags
        self.assertEqual((flag.path, flag.reason), ("src/new.ts", "This file is new, so a rule cannot explain it."))


class TierTest(DigestCase):
    def test_tiers_counts_and_lines(self) -> None:
        self.make(
            {
                "a.py": "a = 1\n",
                "b.py": "b = 1\n",
                "c.py": "c = 1\n",
                "d.py": "d = 1\n",
                "src/a.ts": A_TS,
                "src/b.ts": B_TS,
                "gen/x.js": "x\n",
                "e.txt": "e\n",
                "trail.py": "t  \n",
            },
            {
                "a.py": "a = 2\n",
                "b.py": "b = 2\n",
                "c.py": "c = 2\n",
                "d.py": "d = 2\nd2 = 3\n",
                "src/a.ts": renamed(A_TS),
                "src/b.ts": renamed(B_TS).replace("await loadUser(id);", "loadUser(id);"),
                "gen/x.js": "y\nz\n",
                "e.txt": "f\n",
                "trail.py": "t\n",
            },
        )
        spec = make_spec(
            [sub_group("rename", ["src/*.ts"], "fetchUser", "loadUser"), word_group("gen", ["gen/*"])],
            # d.py is safe then medium, b.py medium then safe: read either way
            [
                chapter("core", "attention", "a.py"),
                chapter("docs", "safe", "c.py", "d.py"),
                chapter("mid", "medium", "b.py", "d.py"),
                chapter("extra", "safe", "b.py"),
            ],
            ["e.txt"],
        )
        files = build_tour.load_changed_files(self.repo.path, self.base, self.head)
        d = digest.classify(spec, files, self.repo.path, self.base, self.head, 3)
        self.assertEqual(
            d.tiers,
            {
                "a.py": "read",
                "b.py": "read",
                "c.py": "skim",
                "d.py": "read",
                "src/a.ts": "matched",
                "src/b.ts": "flagged",
                "gen/x.js": "word",
                "e.txt": "word",
                "trail.py": "matched",
            },
        )
        self.assertEqual([g.id for g in d.groups], ["rename", "gen", "line-ends", "everything-else"])
        self.assertEqual(d.counts, {"flagged": 1, "read": 3, "skim": 1, "matched": 2, "word": 2})
        self.assertEqual(d.seed, 3)
        size = {p: len(fd.added) + len(fd.removed) for p, fd in files.items()}
        self.assertEqual(d.lines["total"], sum(size.values()))
        self.assertEqual(d.lines["read"], sum(size[p] for p in ("a.py", "b.py", "c.py", "d.py", "src/b.ts")))
        self.assertEqual(d.lines["matched"], size["src/a.ts"] + size["trail.py"])
        self.assertEqual(d.lines["word"], size["gen/x.js"] + size["e.txt"])
        self.assertEqual(d.lines["read"] + d.lines["matched"] + d.lines["word"], d.lines["total"])
        # both word groups have one file each, so each sample is that file's only run, on the new side
        self.assertEqual(d.lines["sampled"], len(files["gen/x.js"].added) + len(files["e.txt"].added))


class RunsTest(unittest.TestCase):
    def test_runs(self) -> None:
        fd = build_tour.FileDiff(path="x", status="M", added={1, 2, 5}, removed={3})
        self.assertEqual(digest.runs(fd), [("new", 1, 2), ("new", 5, 5)])
        fd = build_tour.FileDiff(path="x", status="M", removed={3, 4, 9})
        self.assertEqual(digest.runs(fd), [("old", 3, 4), ("old", 9, 9)])
        self.assertEqual(digest.runs(build_tour.FileDiff(path="x", status="M", binary=True)), [])
        self.assertEqual(digest.runs(build_tour.FileDiff(path="x", status="R")), [])


class SampleTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.tmp = tempfile.TemporaryDirectory()
        repo = Repo(Path(cls.tmp.name) / "repo")
        base_text = "".join(f"row {n}\n" for n in range(1, 41))
        base: dict[str, str] = {f"gen30/f{i:02}.txt": base_text for i in range(30)}
        base["big/one.txt"] = "".join(f"line {n}\n" for n in range(1, 101))
        repo.put(base)
        cls.base = repo.commit("base")
        head: dict[str, str] = {}
        for i in range(30):
            changed = {5, 15, 25} | (set(range(30, 36)) if i == 17 else set())
            head[f"gen30/f{i:02}.txt"] = "".join(f"ROW {n}\n" if n in changed else f"row {n}\n" for n in range(1, 41))
        head.update({f"gen50/f{i:02}.txt": f"value {i}\n" for i in range(50)})
        head.update({f"gen200/f{i:03}.txt": f"v{i}\n" for i in range(200)})
        head["big/one.txt"] = "".join(f"LINE {n}\n" if 11 <= n <= 70 else f"line {n}\n" for n in range(1, 101))
        repo.put(head)
        cls.head = repo.commit("head")
        cls.root = repo.path
        cls.files = build_tour.load_changed_files(repo.path, cls.base, cls.head)
        cls.spec = make_spec(
            [
                word_group("g30", ["gen30/*"]),
                word_group("g50", ["gen50/*"], "bulk"),
                word_group("g200", ["gen200/*"], "lockfile"),
                word_group("big", ["big/*"]),
            ]
        )

    @classmethod
    def tearDownClass(cls) -> None:
        cls.tmp.cleanup()

    def run_seed(self, seed: int) -> digest.Digest:
        return digest.classify(self.spec, self.files, self.root, self.base, self.head, seed)

    def test_same_seed_same_result(self) -> None:
        self.assertEqual(self.run_seed(7), self.run_seed(7))

    def test_different_seeds_pick_differently(self) -> None:
        picks = {tuple((s.path, s.start) for s in group_of(self.run_seed(seed), "g30").samples) for seed in range(10)}
        self.assertGreater(len(picks), 1)

    def test_largest_file_first(self) -> None:
        for seed in range(10):
            samples = group_of(self.run_seed(seed), "g30").samples
            self.assertEqual(samples[0].path, "gen30/f17.txt")
            self.assertEqual(len({s.path for s in samples}), len(samples))

    def test_sample_counts(self) -> None:
        d = self.run_seed(1)
        self.assertEqual([len(group_of(d, gid).samples) for gid in ("g30", "g50", "g200", "big")], [3, 5, 8, 1])

    def test_sample_runs_are_widened_and_cut(self) -> None:
        d = self.run_seed(1)
        self.assertEqual(group_of(d, "big").samples, [digest.Sample("big/one.txt", "new", 9, 48)])
        valid = {(3, 7), (13, 17), (23, 27), (28, 37)}
        for s in group_of(d, "g30").samples:
            self.assertEqual(s.side, "new")
            self.assertIn((s.start, s.end), valid)

    def test_sampled_lines(self) -> None:
        d = self.run_seed(1)
        expected = 0
        for g in d.groups:
            for s in g.samples:
                fd = self.files[s.path]
                changed = fd.added if s.side == "new" else fd.removed
                expected += sum(1 for n in range(s.start, s.end + 1) if n in changed)
        self.assertEqual(d.lines["sampled"], expected)
        self.assertEqual(sum(1 for n in range(9, 49) if n in self.files["big/one.txt"].added), 38)

    def test_files_are_not_mutated(self) -> None:
        before = {p: (set(fd.added), set(fd.removed)) for p, fd in self.files.items()}
        self.run_seed(2)
        self.assertEqual({p: (set(fd.added), set(fd.removed)) for p, fd in self.files.items()}, before)


if __name__ == "__main__":
    unittest.main()
